version: '3'

services:
  admin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    restart: always
    command: npm run dev
    volumes:
      - ./:/app:delegated
      - /app/node_modules
      - /app/.next